version: "2.4"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lgia_backend
    restart: unless-stopped
    depends_on:
      postgis:
        condition: service_healthy
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - PG_HOST=postgis
      - PG_USER=postgres
      - PG_PASSWORD=${PG_PASSWORD:-1234}
      - PG_NAME=lgia
      - PG_PORT=5432
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - lgia_network

  postgis:
    image: imresamu/postgis:17-3.5-alpine
    container_name: lgia_postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${PG_PASSWORD:-1234}
    ports:
      - "5433:5432"
    volumes:
      - ./postgis:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d lgia" ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 60s
    networks:
      - lgia_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lgia_frontend
    working_dir: /app
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    networks:
      - lgia_network

volumes:
  pgdata:


networks:
  lgia_network:
    driver: bridge
